INSERT INTO v8aaakav2nzn5tmh.departments(id,name)
    VALUES (1,"チームX");
INSERT INTO v8aaakav2nzn5tmh.departments(id,name)
    VALUES (2,"チームY");
INSERT INTO v8aaakav2nzn5tmh.employees(code,department_id,last_name,first_name,role,password,delete_flg,created_at,updated_at,email)
     VALUES ("9999",1,"管理者","A","ADMIN","$2a$10$PpSqsG6kVXXSBXDzx5h5d..YrRuUEEjfifp3SWVU5pJRA1qOfbUdS",0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"takku1226000@gmail.com");
INSERT INTO v8aaakav2nzn5tmh.employees(code,department_id,last_name,first_name,role,password,delete_flg,created_at,updated_at,email)
     VALUES ("9998",1,"田中","太郎","GENERAL","$2a$10$l16EO7683g5HY3KZk9Uh8e2cvj7Ipn7LQszprAHlj1EceATk8kGYS",0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"kagoshima2930@ssk-kan.co.jp");
INSERT INTO v8aaakav2nzn5tmh.employees(code,department_id,last_name,first_name,role,password,delete_flg,created_at,updated_at,email)
     VALUES ("9997",1,"渡辺","次郎","GENERAL","$2a$10$8l0S8yqGya5.zDkg6CQTKeOGoCzfyFsOHXirFN/tvRfBATrIstHqW",0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"takku1226000@gmail.com");
INSERT INTO v8aaakav2nzn5tmh.reports(report_month,employee_code,delete_flg,submitted_at,updated_at,content_business,time_worked,time_over,rate_business,rate_study,trend_business,content_member,content_customer,content_problem,evaluation_business,evaluation_study,goal_business,goal_study,content_company,content_others,complete_flg,comment,report_deadline,approval_flg)
     VALUES ("2025-02",9999,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"業務内容 サンプルテキスト",160,10,100,90,80,"その他メンバー関連内容 サンプルテキスト","お客様情報 サンプルテキスト","問題点内容 サンプルテキスト","自己評価（先月業務目標） サンプルテキスト","自己評価（先月学習目標） サンプルテキスト","今月業務目標 サンプルテキスト","今月学習目標 サンプルテキスト","会社関係 サンプルテキスト","その他 サンプルテキスト",0,"comment サンプルテキスト",'2024-10-31',NULL);
INSERT INTO v8aaakav2nzn5tmh.reports(report_month,employee_code,delete_flg,submitted_at,updated_at,content_business,time_worked,time_over,rate_business,rate_study,trend_business,content_member,content_customer,content_problem,evaluation_business,evaluation_study,goal_business,goal_study,content_company,content_others,complete_flg,comment,report_deadline,approval_flg)
     VALUES ("2025-02",9998,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"業務内容 サンプルテキスト",160,10,100,90,80,"その他メンバー関連内容 サンプルテキスト","お客様情報 サンプルテキスト","問題点内容 サンプルテキスト","自己評価（先月業務目標） サンプルテキスト","自己評価（先月学習目標） サンプルテキスト","今月業務目標 サンプルテキスト","今月学習目標 サンプルテキスト","会社関係 サンプルテキスト","その他 サンプルテキスト",1,"comment サンプルテキスト",'2024-10-31',NULL);
INSERT INTO v8aaakav2nzn5tmh.reports(report_month,employee_code,delete_flg,submitted_at,updated_at,content_business,time_worked,time_over,rate_business,rate_study,trend_business,content_member,content_customer,content_problem,evaluation_business,evaluation_study,goal_business,goal_study,content_company,content_others,complete_flg,comment,report_deadline,approval_flg)
     VALUES ("2025-02",9997,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"業務内容 サンプルテキスト",160,10,100,90,80,"その他メンバー関連内容 サンプルテキスト","お客様情報 サンプルテキスト","問題点内容 サンプルテキスト","自己評価（先月業務目標） サンプルテキスト","自己評価（先月学習目標） サンプルテキスト","今月業務目標 サンプルテキスト","今月学習目標 サンプルテキスト","会社関係 サンプルテキスト","その他 サンプルテキスト",1,"",'2024-10-31',NULL);
INSERT INTO v8aaakav2nzn5tmh.reports(report_month,employee_code,delete_flg,submitted_at,updated_at,content_business,time_worked,time_over,rate_business,rate_study,trend_business,content_member,content_customer,content_problem,evaluation_business,evaluation_study,goal_business,goal_study,content_company,content_others,complete_flg,comment,report_deadline,approval_flg)
     VALUES ("2025-02",9997,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"業務内容 サンプルテキスト",160,10,100,90,80,"その他メンバー関連内容 サンプルテキスト","お客様情報 サンプルテキスト","問題点内容 サンプルテキスト","自己評価（先月業務目標） サンプルテキスト","自己評価（先月学習目標） サンプルテキスト","今月業務目標 サンプルテキスト","今月学習目標 サンプルテキスト","会社関係 サンプルテキスト","その他 サンプルテキスト",0,"",'2024-09-30',NULL);
INSERT INTO v8aaakav2nzn5tmh.reports(report_month,employee_code,delete_flg,submitted_at,updated_at,content_business,time_worked,time_over,rate_business,rate_study,trend_business,content_member,content_customer,content_problem,evaluation_business,evaluation_study,goal_business,goal_study,content_company,content_others,complete_flg,comment,report_deadline,approval_flg)
     VALUES ("2024-08",9997,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"業務内容 サンプルテキスト",160,10,100,90,80,"その他メンバー関連内容 サンプルテキスト","お客様情報 サンプルテキスト","問題点内容 サンプルテキスト","自己評価（先月業務目標） サンプルテキスト","自己評価（先月学習目標） サンプルテキスト","今月業務目標 サンプルテキスト","今月学習目標 サンプルテキスト","会社関係 サンプルテキスト","その他 サンプルテキスト",0,"comment サンプルテキスト",'2024-08-31',NULL);
INSERT INTO v8aaakav2nzn5tmh.reports(report_month,employee_code,delete_flg,submitted_at,updated_at,content_business,time_worked,time_over,rate_business,rate_study,trend_business,content_member,content_customer,content_problem,evaluation_business,evaluation_study,goal_business,goal_study,content_company,content_others,complete_flg,comment,report_deadline,approval_flg)
     VALUES ("2024-07",9997,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"業務内容 サンプルテキスト",160,10,100,90,80,"その他メンバー関連内容 サンプルテキスト","お客様情報 サンプルテキスト","問題点内容 サンプルテキスト","自己評価（先月業務目標） サンプルテキスト","自己評価（先月学習目標） サンプルテキスト","今月業務目標 サンプルテキスト","今月学習目標 サンプルテキスト","会社関係 サンプルテキスト","その他 サンプルテキスト",0,"comment サンプルテキスト",'2024-07-31',NULL);
INSERT INTO v8aaakav2nzn5tmh.reports(report_month,employee_code,delete_flg,submitted_at,updated_at,content_business,time_worked,time_over,rate_business,rate_study,trend_business,content_member,content_customer,content_problem,evaluation_business,evaluation_study,goal_business,goal_study,content_company,content_others,complete_flg,comment,report_deadline,approval_flg)
     VALUES ("2024-06",9997,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"業務内容 サンプルテキスト",160,10,100,90,80,"その他メンバー関連内容 サンプルテキスト","お客様情報 サンプルテキスト","問題点内容 サンプルテキスト","自己評価（先月業務目標） サンプルテキスト","自己評価（先月学習目標） サンプルテキスト","今月業務目標 サンプルテキスト","今月学習目標 サンプルテキスト","会社関係 サンプルテキスト","その他 サンプルテキスト",0,"comment サンプルテキスト",'2024-06-30',NULL);
INSERT INTO v8aaakav2nzn5tmh.reports(report_month,employee_code,delete_flg,submitted_at,updated_at,content_business,time_worked,time_over,rate_business,rate_study,trend_business,content_member,content_customer,content_problem,evaluation_business,evaluation_study,goal_business,goal_study,content_company,content_others,complete_flg,comment,report_deadline,approval_flg)
     VALUES ("2024-05",9997,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,"業務内容 サンプルテキスト",160,10,100,90,80,"その他メンバー関連内容 サンプルテキスト","お客様情報 サンプルテキスト","問題点内容 サンプルテキスト","自己評価（先月業務目標） サンプルテキスト","自己評価（先月学習目標） サンプルテキスト","今月業務目標 サンプルテキスト","今月学習目標 サンプルテキスト","会社関係 サンプルテキスト","その他 サンプルテキスト",0,"comment サンプルテキスト",'2024-05-31',NULL);
